# Banach space

https://en.wikipedia.org/wiki/Banach_space

In [1]:
import warnings
warnings.filterwarnings("ignore")

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Input
symbol = 'AMD'
start = '2014-01-01'
end = '2019-01-01'

# Read data
dataset = yf.download(symbol, start, end)

# Prepare data
data = dataset['Adj Close']

# Define a vector in the Banach space
vector = np.array(data)

# Define a norm function
def norm(vector):
    return np.linalg.norm(vector)

# Check if the space is complete (i.e., a Banach space)
def is_complete(vector_space):
    for sequence in vector_space:
        if not np.all(np.isfinite(sequence)):
            return False
    return True

# Create a sequence of vectors
sequence_of_vectors = [vector / (n + 1) for n in range(10)]

# Check if the sequence forms a Banach space
if is_complete(sequence_of_vectors):
    print("The sequence forms a Banach space.")
else:
    print("The sequence does not form a Banach space.")

[*********************100%***********************]  1 of 1 completed
The sequence forms a Banach space.


In [2]:
sequence_of_vectors

[array([ 3.95000005,  4.        ,  4.13000011, ..., 17.48999977,
        17.81999969, 18.45999908]),
 array([1.97500002, 2.        , 2.06500006, ..., 8.74499989, 8.90999985,
        9.22999954]),
 array([1.31666668, 1.33333333, 1.3766667 , ..., 5.82999992, 5.9399999 ,
        6.15333303]),
 array([0.98750001, 1.        , 1.03250003, ..., 4.37249994, 4.45499992,
        4.61499977]),
 array([0.79000001, 0.8       , 0.82600002, ..., 3.49799995, 3.56399994,
        3.69199982]),
 array([0.65833334, 0.66666667, 0.68833335, ..., 2.91499996, 2.96999995,
        3.07666651]),
 array([0.56428572, 0.57142857, 0.59000002, ..., 2.4985714 , 2.54571424,
        2.63714273]),
 array([0.49375001, 0.5       , 0.51625001, ..., 2.18624997, 2.22749996,
        2.30749989]),
 array([0.43888889, 0.44444444, 0.4588889 , ..., 1.94333331, 1.97999997,
        2.05111101]),
 array([0.395     , 0.4       , 0.41300001, ..., 1.74899998, 1.78199997,
        1.84599991])]