# Cosine Similarity 

## Cosine similarity metric finds the normalized dot product of the two attributes. By determining the cosine similarity, we would effectively try to find the cosine of the angle between the two objects. The cosine of 0° is 1, and it is less than 1 for any other angle.

In [1]:
import numpy as np
from math import sqrt
from sklearn.metrics.pairwise import cosine_similarity
from scipy.spatial.distance import cdist

import warnings
warnings.filterwarnings("ignore") 

# yfinance is used to fetch data 
import yfinance as yf
yf.pdr_override()

In [2]:
symbol = 'AMD'

start = '2018-01-01'
end = '2019-01-01'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 completed


Open   High    Low  Close  Adj Close     Volume
Date                                                        
2018-01-02  10.42  11.02  10.34  10.98      10.98   44146300
2018-01-03  11.61  12.14  11.36  11.55      11.55  154066700
2018-01-04  12.10  12.43  11.97  12.12      12.12  109503000
2018-01-05  12.19  12.22  11.66  11.88      11.88   63808900
2018-01-08  12.01  12.30  11.85  12.28      12.28   63346000

In [3]:
dataset.tail()

Open       High        Low      Close  Adj Close     Volume
Date                                                                        
2018-12-24  16.520000  17.219999  16.370001  16.650000  16.650000   62933100
2018-12-26  16.879999  17.910000  16.030001  17.900000  17.900000  108811800
2018-12-27  17.430000  17.740000  16.440001  17.490000  17.490000  111373000
2018-12-28  17.530001  18.309999  17.139999  17.820000  17.820000  109214400
2018-12-31  18.150000  18.510000  17.850000  18.459999  18.459999   84732200

In [4]:
Open = np.array(dataset['Open'])
Close = np.array(dataset['Adj Close'])

In [5]:
Open.shape

(251,)

In [6]:
Close.shape

(251,)

In [7]:
Close = Close.reshape(251, -1)
Close

array([[10.97999954],
       [11.55000019],
       [12.11999989],
       [11.88000011],
       [12.27999973],
       [11.81999969],
       [11.96000004],
       [12.14000034],
       [12.02000046],
       [11.90999985],
       [12.18000031],
       [12.47000027],
       [12.59000015],
       [12.64999962],
       [12.93999958],
       [12.71000004],
       [12.40999985],
       [12.94999981],
       [13.31999969],
       [12.86999989],
       [13.73999977],
       [13.25      ],
       [12.44999981],
       [11.56999969],
       [11.64999962],
       [11.60000038],
       [11.22000027],
       [11.31000042],
       [11.68000031],
       [11.77999973],
       [12.19999981],
       [12.18999958],
       [11.81999969],
       [12.02000046],
       [11.72000027],
       [11.84000015],
       [12.06999969],
       [12.42000008],
       [12.52999973],
       [12.10999966],
       [11.89999962],
       [11.81000042],
       [11.90999985],
       [11.76000023],
       [12.23999977],
       [11

In [8]:
Open = Open.reshape(251, -1)
Open

array([[10.42000008],
       [11.60999966],
       [12.10000038],
       [12.18999958],
       [12.01000023],
       [12.        ],
       [11.63000011],
       [12.06999969],
       [11.81999969],
       [12.05000019],
       [11.89999962],
       [12.18000031],
       [12.56000042],
       [12.60999966],
       [12.81999969],
       [13.02000046],
       [12.77999973],
       [12.69999981],
       [13.13000011],
       [13.11999989],
       [13.23999977],
       [13.61999989],
       [13.05000019],
       [12.05000019],
       [11.03999996],
       [11.69999981],
       [11.72000027],
       [11.53999996],
       [11.47000027],
       [11.60000038],
       [11.72000027],
       [12.39999962],
       [12.10999966],
       [11.72000027],
       [12.11999989],
       [11.81999969],
       [11.94999981],
       [12.14000034],
       [12.43000031],
       [12.65999985],
       [12.26000023],
       [11.67000008],
       [11.68999958],
       [12.01000023],
       [11.57999992],
       [12

In [9]:
# Cosine Similarity sklearn
dist_out_sk = cosine_similarity(Open,Close)
dist_out_sk

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [10]:
# Cosine Similarity scipy
dist_out_sc = cdist(Open,Close)
dist_out_sc

array([[0.55999947, 1.13000011, 1.69999981, ..., 7.06999969, 7.39999962,
        8.03999901],
       [0.63000011, 0.05999947, 0.51000023, ..., 5.88000011, 6.21000004,
        6.84999943],
       [1.12000084, 0.55000019, 0.0199995 , ..., 5.38999939, 5.71999931,
        6.3599987 ],
       ...,
       [6.45000076, 5.88000011, 5.31000042, ..., 0.05999947, 0.38999939,
        1.02999878],
       [6.55000114, 5.9800005 , 5.4100008 , ..., 0.04000092, 0.28999901,
        0.9299984 ],
       [7.17000008, 6.59999943, 6.02999973, ..., 0.65999985, 0.32999992,
        0.30999947]])

In [11]:
dataset = yf.download(symbol,start,end)


[*********************100%***********************]  1 of 1 completed


In [12]:
Open = np.array(dataset[['Open']])
Close = np.array(dataset[['Adj Close']])

In [13]:
Open = Open.reshape(-1, 251)
Open

array([[10.42000008, 11.60999966, 12.10000038, 12.18999958, 12.01000023,
        12.        , 11.63000011, 12.06999969, 11.81999969, 12.05000019,
        11.89999962, 12.18000031, 12.56000042, 12.60999966, 12.81999969,
        13.02000046, 12.77999973, 12.69999981, 13.13000011, 13.11999989,
        13.23999977, 13.61999989, 13.05000019, 12.05000019, 11.03999996,
        11.69999981, 11.72000027, 11.53999996, 11.47000027, 11.60000038,
        11.72000027, 12.39999962, 12.10999966, 11.72000027, 12.11999989,
        11.81999969, 11.94999981, 12.14000034, 12.43000031, 12.65999985,
        12.26000023, 11.67000008, 11.68999958, 12.01000023, 11.57999992,
        12.39999962, 12.02999973, 11.76000023, 11.5       , 11.69999981,
        11.43000031, 11.48999977, 11.40999985, 11.40999985, 11.15999985,
        11.10000038, 10.90999985, 10.71000004, 10.51000023,  9.98999977,
         9.93999958,  9.98999977,  9.63000011,  9.07999992, 10.05000019,
         9.82999992,  9.75      ,  9.75      ,  9.8

In [14]:
Close = Close.reshape(-1, 251)
Close

array([[10.97999954, 11.55000019, 12.11999989, 11.88000011, 12.27999973,
        11.81999969, 11.96000004, 12.14000034, 12.02000046, 11.90999985,
        12.18000031, 12.47000027, 12.59000015, 12.64999962, 12.93999958,
        12.71000004, 12.40999985, 12.94999981, 13.31999969, 12.86999989,
        13.73999977, 13.25      , 12.44999981, 11.56999969, 11.64999962,
        11.60000038, 11.22000027, 11.31000042, 11.68000031, 11.77999973,
        12.19999981, 12.18999958, 11.81999969, 12.02000046, 11.72000027,
        11.84000015, 12.06999969, 12.42000008, 12.52999973, 12.10999966,
        11.89999962, 11.81000042, 11.90999985, 11.76000023, 12.23999977,
        11.97000027, 11.69999981, 11.52000046, 11.64000034, 11.35999966,
        11.46000004, 11.47000027, 11.43000031, 11.10999966, 11.26000023,
        10.90999985, 10.63000011, 10.43999958, 10.        ,  9.81000042,
        10.05000019,  9.52999973,  9.55000019,  9.77000046, 10.02000046,
         9.60999966,  9.52999973,  9.97999954,  9.8

In [15]:
print(cosine_similarity(Open, Close))


[[0.99921178]]


In [16]:
print(cdist(Open, Close))

[[11.50391653]]
