# Linear Algebra

In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore") 

# yfinance is used to fetch data 
import yfinance as yf
yf.pdr_override()

In [2]:
symbol = 'AMD'

start = '2020-01-01'
end = '2022-01-01'

# Read data 
dataset = yf.download(symbol,start,end)

# View Columns
dataset.head()

[*********************100%***********************]  1 of 1 completed


Open       High        Low      Close  Adj Close    Volume
Date                                                                       
2020-01-02  46.860001  49.250000  46.630001  49.099998  49.099998  80331100
2020-01-03  48.029999  49.389999  47.540001  48.599998  48.599998  73127400
2020-01-06  48.020000  48.860001  47.860001  48.389999  48.389999  47934900
2020-01-07  49.349998  49.389999  48.040001  48.250000  48.250000  58061400
2020-01-08  47.849998  48.299999  47.139999  47.830002  47.830002  53767000

In [3]:
dataset['Returns'] = dataset['Adj Close'].pct_change() 
dataset['Returns'] = dataset['Adj Close'].dropna()

In [4]:
Returns = np.array(dataset['Returns'])
Open = np.array(dataset['Open'])
Close = np.array(dataset['Adj Close'])
High = np.array(dataset['High'])
Low = np.array(dataset['Low'])

In [5]:
Close = np.round(Close, 2)
Close

array([ 49.1 ,  48.6 ,  48.39,  48.25,  47.83,  48.97,  48.17,  48.75,
        48.21,  48.55,  49.77,  50.93,  51.05,  51.43,  51.71,  50.35,
        49.26,  50.53,  47.51,  48.78,  47.  ,  48.02,  49.45,  49.84,
        49.32,  49.73,  52.26,  53.8 ,  53.89,  54.53,  55.31,  56.89,
        58.9 ,  57.27,  53.28,  49.12,  47.57,  47.49,  44.01,  45.48,
        47.46,  46.75,  50.11,  48.11,  48.59,  43.27,  45.38,  45.7 ,
        39.01,  43.9 ,  38.71,  41.88,  39.12,  39.82,  39.61,  41.64,
        46.22,  44.63,  47.5 ,  46.58,  47.86,  45.48,  43.66,  44.49,
        42.59,  47.52,  47.56,  48.79,  48.38,  50.94,  54.93,  54.99,
        56.95,  56.6 ,  56.97,  52.92,  55.92,  55.9 ,  56.18,  56.49,
        55.51,  53.66,  52.39,  49.88,  52.56,  52.19,  52.16,  51.95,
        53.19,  55.74,  53.76,  52.18,  54.51,  54.2 ,  54.59,  55.47,
        56.39,  54.65,  55.17,  53.19,  52.74,  51.74,  53.8 ,  53.63,
        53.54,  52.73,  52.63,  53.1 ,  52.97,  56.39,  57.44,  52.83,
      

In [6]:
import collections

print([item for item, count in collections.Counter(Close).items() if count > 1])

[53.8, 45.48, 52.39, 53.19, 56.39, 85.31, 86.71, 81.84, 82.42, 81.09, 82.54, 78.06, 81.56, 81.35, 81.43, 92.66, 79.06, 82.76, 78.55, 106.15]


## Vectors (Rank 1 Tensors) in NumPy

In [7]:
x = [item for item, count in collections.Counter(Close).items() if count > 1]
x

[53.8,
 45.48,
 52.39,
 53.19,
 56.39,
 85.31,
 86.71,
 81.84,
 82.42,
 81.09,
 82.54,
 78.06,
 81.56,
 81.35,
 81.43,
 92.66,
 79.06,
 82.76,
 78.55,
 106.15]

In [8]:
x = np.array(x)
x

array([ 53.8 ,  45.48,  52.39,  53.19,  56.39,  85.31,  86.71,  81.84,
        82.42,  81.09,  82.54,  78.06,  81.56,  81.35,  81.43,  92.66,
        79.06,  82.76,  78.55, 106.15])

In [9]:
 len(x)

20

In [10]:
x.shape

(20,)

In [11]:
type(x)

numpy.ndarray

In [12]:
x[0]

53.8

In [13]:
type(x[0])

numpy.float64

## Vector Transposition

In [14]:
# Transposing a regular 1-D array has no effect
x_t = x.T
x_t

array([ 53.8 ,  45.48,  52.39,  53.19,  56.39,  85.31,  86.71,  81.84,
        82.42,  81.09,  82.54,  78.06,  81.56,  81.35,  81.43,  92.66,
        79.06,  82.76,  78.55, 106.15])

In [15]:
x_t.shape

(20,)

In [16]:
Open = np.round(Open, 2)
Open

array([ 46.86,  48.03,  48.02,  49.35,  47.85,  48.94,  49.26,  48.66,
        48.64,  48.23,  49.17,  50.2 ,  50.96,  51.63,  51.34,  52.28,
        48.45,  50.03,  47.84,  46.49,  48.4 ,  46.4 ,  49.21,  50.29,
        48.8 ,  48.91,  49.47,  53.22,  54.53,  53.43,  55.19,  54.94,
        57.99,  58.44,  56.71,  48.18,  51.14,  47.7 ,  45.38,  41.36,
        47.42,  49.03,  48.25,  48.68,  49.44,  43.03,  45.41,  44.19,
        42.  ,  42.2 ,  39.08,  40.19,  39.54,  39.56,  41.51,  40.62,
        44.04,  46.79,  45.78,  46.32,  47.24,  47.93,  44.18,  43.4 ,
        44.3 ,  44.3 ,  48.96,  48.07,  49.65,  48.47,  52.24,  53.73,
        55.96,  57.35,  55.98,  56.9 ,  54.91,  56.65,  55.1 ,  57.44,
        57.16,  54.53,  53.43,  51.07,  49.82,  53.43,  52.42,  52.93,
        52.15,  52.9 ,  56.21,  54.04,  52.1 ,  53.32,  54.98,  54.39,
        56.55,  56.68,  54.77,  56.01,  53.27,  52.25,  52.07,  53.31,
        53.45,  53.6 ,  52.59,  52.99,  53.3 ,  52.95,  57.2 ,  55.94,
      

In [17]:
y = [item for item, count in collections.Counter(Open).items() if count > 1]
y

[54.53,
 53.43,
 44.3,
 52.9,
 56.68,
 53.3,
 78.03,
 85.05,
 82.8,
 81.4,
 81.75,
 82.55,
 83.4,
 75.85,
 81.32,
 81.21,
 92.1,
 88.15,
 84.28,
 81.61]

In [18]:
y = np.array([y])

In [19]:
y.shape

(1, 20)

In [20]:
y_t = y.T
y_t

array([[54.53],
       [53.43],
       [44.3 ],
       [52.9 ],
       [56.68],
       [53.3 ],
       [78.03],
       [85.05],
       [82.8 ],
       [81.4 ],
       [81.75],
       [82.55],
       [83.4 ],
       [75.85],
       [81.32],
       [81.21],
       [92.1 ],
       [88.15],
       [84.28],
       [81.61]])

In [21]:
y_t.shape 

(20, 1)

In [22]:
y_t.T 

array([[54.53, 53.43, 44.3 , 52.9 , 56.68, 53.3 , 78.03, 85.05, 82.8 ,
        81.4 , 81.75, 82.55, 83.4 , 75.85, 81.32, 81.21, 92.1 , 88.15,
        84.28, 81.61]])

In [23]:
y_t.T.shape

(1, 20)

## Torch and Tensorflow

In [24]:

import torch
import tensorflow as tf


In [25]:
x_pt = torch.tensor(x)
x_pt

tensor([ 53.8000,  45.4800,  52.3900,  53.1900,  56.3900,  85.3100,  86.7100,
         81.8400,  82.4200,  81.0900,  82.5400,  78.0600,  81.5600,  81.3500,
         81.4300,  92.6600,  79.0600,  82.7600,  78.5500, 106.1500],
       dtype=torch.float64)

In [26]:

x_tf = tf.Variable(x)
x_tf


Instructions for updating:
Colocations handled automatically by placer.


<tf.Variable 'Variable:0' shape=(20,) dtype=float64_ref>

## $L^2$ Norm

In [27]:
x

array([ 53.8 ,  45.48,  52.39,  53.19,  56.39,  85.31,  86.71,  81.84,
        82.42,  81.09,  82.54,  78.06,  81.56,  81.35,  81.43,  92.66,
        79.06,  82.76,  78.55, 106.15])

In [28]:
np.linalg.norm(x)

347.1452995504908

In [29]:
np.dot(x,x)

120509.859

## $L^1$ Norm

In [30]:
norm_a_l1 =np.linalg.norm(x, ord=1)

In [31]:
print("x =", x, "\n")

print("L1 norm of x:", norm_a_l1)

x = [ 53.8   45.48  52.39  53.19  56.39  85.31  86.71  81.84  82.42  81.09
  82.54  78.06  81.56  81.35  81.43  92.66  79.06  82.76  78.55 106.15] 

L1 norm of x: 1522.74


### Max Norm

In [32]:
np.max([np.abs(x)])



106.15

### Orthogonal Vectors

In [33]:
i = np.array([x])
i = i.T
i.shape

(20, 1)

In [34]:
j = np.array(y)
j.shape




(1, 20)

In [35]:
np.dot(i, j)

array([[2933.714 , 2874.534 , 2383.34  , 2846.02  , 3049.384 , 2867.54  ,
        4198.014 , 4575.69  , 4454.64  , 4379.32  , 4398.15  , 4441.19  ,
        4486.92  , 4080.73  , 4375.016 , 4369.098 , 4954.98  , 4742.47  ,
        4534.264 , 4390.618 ],
       [2480.0244, 2429.9964, 2014.764 , 2405.892 , 2577.8064, 2424.084 ,
        3548.8044, 3868.074 , 3765.744 , 3702.072 , 3717.99  , 3754.374 ,
        3793.032 , 3449.658 , 3698.4336, 3693.4308, 4188.708 , 4009.062 ,
        3833.0544, 3711.6228],
       [2856.8267, 2799.1977, 2320.877 , 2771.431 , 2969.4652, 2792.387 ,
        4087.9917, 4455.7695, 4337.892 , 4264.546 , 4282.8825, 4324.7945,
        4369.326 , 3973.7815, 4260.3548, 4254.5919, 4825.119 , 4618.1785,
        4415.4292, 4275.5479],
       [2900.4507, 2841.9417, 2356.317 , 2813.751 , 3014.8092, 2835.027 ,
        4150.4157, 4523.8095, 4404.132 , 4329.666 , 4348.2825, 4390.8345,
        4436.046 , 4034.4615, 4325.4108, 4319.5599, 4898.799 , 4688.6985,
        4482.8532, 

## Convert Array to 2-D Mastrix

In [36]:
x

array([ 53.8 ,  45.48,  52.39,  53.19,  56.39,  85.31,  86.71,  81.84,
        82.42,  81.09,  82.54,  78.06,  81.56,  81.35,  81.43,  92.66,
        79.06,  82.76,  78.55, 106.15])

In [37]:
x.shape

(20,)

In [38]:
arr_2d = np.reshape(x, (4, 5))

In [39]:
print('1D Numpy array:')
print(x)
print("\n")
print('2D Numpy array:')
print(arr_2d)

1D Numpy array:
[ 53.8   45.48  52.39  53.19  56.39  85.31  86.71  81.84  82.42  81.09
  82.54  78.06  81.56  81.35  81.43  92.66  79.06  82.76  78.55 106.15]


2D Numpy array:
[[ 53.8   45.48  52.39  53.19  56.39]
 [ 85.31  86.71  81.84  82.42  81.09]
 [ 82.54  78.06  81.56  81.35  81.43]
 [ 92.66  79.06  82.76  78.55 106.15]]


In [40]:
arr_2d.shape

(4, 5)

In [41]:
arr_2d.size

20

In [42]:
# Select left column of matrix X (zero-indexed)
arr_2d[:,0]



array([53.8 , 85.31, 82.54, 92.66])

In [43]:
# Select middle row of matrix X: 
arr_2d[1,:]

array([85.31, 86.71, 81.84, 82.42, 81.09])

In [44]:
# Another slicing-by-index example: 
arr_2d[0:2, 0:2]



array([[53.8 , 45.48],
       [85.31, 86.71]])

### Matrices in PyTorch

In [45]:
X_pt = torch.tensor(arr_2d)
X_pt

tensor([[ 53.8000,  45.4800,  52.3900,  53.1900,  56.3900],
        [ 85.3100,  86.7100,  81.8400,  82.4200,  81.0900],
        [ 82.5400,  78.0600,  81.5600,  81.3500,  81.4300],
        [ 92.6600,  79.0600,  82.7600,  78.5500, 106.1500]],
       dtype=torch.float64)

In [46]:
X_pt.shape

torch.Size([4, 5])

In [47]:
X_pt[1,:]

tensor([85.3100, 86.7100, 81.8400, 82.4200, 81.0900], dtype=torch.float64)

### Matrices in TensorFlow

In [48]:
X_tf = tf.Variable(arr_2d)
X_tf

<tf.Variable 'Variable_1:0' shape=(4, 5) dtype=float64_ref>

In [49]:
tf.rank(X_tf)

<tf.Tensor 'Rank:0' shape=() dtype=int32>

In [50]:
tf.shape(X_tf)


<tf.Tensor 'Shape:0' shape=(2,) dtype=int32>

In [51]:
X_tf[1,:]



<tf.Tensor 'strided_slice:0' shape=(5,) dtype=float64>

### Matrix Transposition

In [52]:
X = arr_2d

In [53]:
X

array([[ 53.8 ,  45.48,  52.39,  53.19,  56.39],
       [ 85.31,  86.71,  81.84,  82.42,  81.09],
       [ 82.54,  78.06,  81.56,  81.35,  81.43],
       [ 92.66,  79.06,  82.76,  78.55, 106.15]])

In [54]:
X.T

array([[ 53.8 ,  85.31,  82.54,  92.66],
       [ 45.48,  86.71,  78.06,  79.06],
       [ 52.39,  81.84,  81.56,  82.76],
       [ 53.19,  82.42,  81.35,  78.55],
       [ 56.39,  81.09,  81.43, 106.15]])

In [55]:
X_pt.T

tensor([[ 53.8000,  85.3100,  82.5400,  92.6600],
        [ 45.4800,  86.7100,  78.0600,  79.0600],
        [ 52.3900,  81.8400,  81.5600,  82.7600],
        [ 53.1900,  82.4200,  81.3500,  78.5500],
        [ 56.3900,  81.0900,  81.4300, 106.1500]], dtype=torch.float64)

### Matrix Multiplication

In [56]:
X*3

array([[161.4 , 136.44, 157.17, 159.57, 169.17],
       [255.93, 260.13, 245.52, 247.26, 243.27],
       [247.62, 234.18, 244.68, 244.05, 244.29],
       [277.98, 237.18, 248.28, 235.65, 318.45]])

In [57]:
X*3+3

array([[164.4 , 139.44, 160.17, 162.57, 172.17],
       [258.93, 263.13, 248.52, 250.26, 246.27],
       [250.62, 237.18, 247.68, 247.05, 247.29],
       [280.98, 240.18, 251.28, 238.65, 321.45]])

In [58]:
X_pt*3+3

tensor([[164.4000, 139.4400, 160.1700, 162.5700, 172.1700],
        [258.9300, 263.1300, 248.5200, 250.2600, 246.2700],
        [250.6200, 237.1800, 247.6800, 247.0500, 247.2900],
        [280.9800, 240.1800, 251.2800, 238.6500, 321.4500]],
       dtype=torch.float64)

#### Multiplication operator on two tensors of the same size in PyTorch (or Numpy or TensorFlow) applies element-wise operations. This is the **Hadamard product** (denoted by the $\odot$ operator, e.g., $A \odot B$) *not* **matrix multiplication**: 

In [59]:
A = np.reshape(y, (4, 5))
A 

array([[54.53, 53.43, 44.3 , 52.9 , 56.68],
       [53.3 , 78.03, 85.05, 82.8 , 81.4 ],
       [81.75, 82.55, 83.4 , 75.85, 81.32],
       [81.21, 92.1 , 88.15, 84.28, 81.61]])

In [60]:
X

array([[ 53.8 ,  45.48,  52.39,  53.19,  56.39],
       [ 85.31,  86.71,  81.84,  82.42,  81.09],
       [ 82.54,  78.06,  81.56,  81.35,  81.43],
       [ 92.66,  79.06,  82.76,  78.55, 106.15]])

In [61]:
X * A

array([[2933.714 , 2429.9964, 2320.877 , 2813.751 , 3196.1852],
       [4547.023 , 6765.9813, 6960.492 , 6824.376 , 6600.726 ],
       [6747.645 , 6443.853 , 6802.104 , 6170.3975, 6621.8876],
       [7524.9186, 7281.426 , 7295.294 , 6620.194 , 8662.9015]])

In [62]:
A_p = torch.tensor(A)
A_p

tensor([[54.5300, 53.4300, 44.3000, 52.9000, 56.6800],
        [53.3000, 78.0300, 85.0500, 82.8000, 81.4000],
        [81.7500, 82.5500, 83.4000, 75.8500, 81.3200],
        [81.2100, 92.1000, 88.1500, 84.2800, 81.6100]], dtype=torch.float64)

In [63]:
X_pt * A_p

tensor([[2933.7140, 2429.9964, 2320.8770, 2813.7510, 3196.1852],
        [4547.0230, 6765.9813, 6960.4920, 6824.3760, 6600.7260],
        [6747.6450, 6443.8530, 6802.1040, 6170.3975, 6621.8876],
        [7524.9186, 7281.4260, 7295.2940, 6620.1940, 8662.9015]],
       dtype=torch.float64)

In [64]:
X = X.T
np.dot(A, X) # even though technically dot products is between 2 vectors

array([[13694.5236, 21866.5808, 21203.6274, 23115.0706],
       [19866.3919, 31698.5983, 30791.2638, 33291.1178],
       [21141.9463, 33803.2548, 32785.8871, 35593.6775],
       [22260.8256, 35692.3246, 34583.5937, 37384.7341]])

In [65]:
b_p = torch.tensor(X)
b_p

tensor([[ 53.8000,  85.3100,  82.5400,  92.6600],
        [ 45.4800,  86.7100,  78.0600,  79.0600],
        [ 52.3900,  81.8400,  81.5600,  82.7600],
        [ 53.1900,  82.4200,  81.3500,  78.5500],
        [ 56.3900,  81.0900,  81.4300, 106.1500]], dtype=torch.float64)

In [66]:
torch.matmul(A_p, b_p)

tensor([[13694.5236, 21866.5808, 21203.6274, 23115.0706],
        [19866.3919, 31698.5983, 30791.2638, 33291.1178],
        [21141.9463, 33803.2548, 32785.8871, 35593.6775],
        [22260.8256, 35692.3246, 34583.5937, 37384.7341]], dtype=torch.float64)

### Matrix Inversion

In [67]:
# Inverse matrix is only for square matrix
arr_2d 

array([[ 53.8 ,  45.48,  52.39,  53.19,  56.39],
       [ 85.31,  86.71,  81.84,  82.42,  81.09],
       [ 82.54,  78.06,  81.56,  81.35,  81.43],
       [ 92.66,  79.06,  82.76,  78.55, 106.15]])

In [68]:
X = np.array([[2, 8], [-5, -6]])
X

array([[ 2,  8],
       [-5, -6]])

In [69]:
Xinv = np.linalg.inv(X)
Xinv

array([[-0.21428571, -0.28571429],
       [ 0.17857143,  0.07142857]])

In [70]:
y = np.array([3, -5])
y

array([ 3, -5])

In [71]:
w = np.dot(Xinv, y)
w

array([0.78571429, 0.17857143])

In [72]:
np.dot(X, w)

array([ 3., -5.])

In [73]:
X_p = torch.tensor([[5, 10], [-6, -8.]]) # note that torch.inverse() requires floats
X_p

tensor([[ 5., 10.],
        [-6., -8.]])

In [74]:
Xinv_p = torch.inverse(X_p)
Xinv_p

tensor([[-0.4000, -0.5000],
        [ 0.3000,  0.2500]])

In [75]:
y_p = torch.tensor([4, -7.])
y_p

tensor([ 4., -7.])

In [76]:
w_p = torch.matmul(Xinv_p, y_p)
w_p

tensor([ 1.9000, -0.5500])

In [77]:
torch.matmul(X_p, w_p)

tensor([ 4.0000, -7.0000])